# docker-compose.yml
services:
  service-name:
    image: express
    ports:
      - "3000:3000"
    environment:
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxteHRod2tvcGFoaHF6eGxobmNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5NDA5NjcsImV4cCI6MjA1NjUxNjk2N30.3N4RtXBJDBKVzWcUUYEv9AsTtbEz45culOubu6YnDvE
    #usually I wouldn't deploy this apikey to production but this is a read only key